blank_issues_enabled: true
contact_links:
  - name: Have any issues to discuss regarding JSON Schema?
    url: https://json-schema.org/slack
    about: Join us on Slack and meet members and contributors.