name: 📝 Documentation
description: Propose changes and improvements to JSON Schema Docs.
labels: ["📝 Documentation", "Status: Triage"]
title: "[📝 Docs]: "
projects: "json-schema-org/16"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to JSON Schema Docs! 📑 👩🏻‍💻 We appreciate your feedback, ideas, and contributions. 
        
        Before filing this issue, please make sure to check if there's already a similar issue open in our [JSON Schema Docs Board](https://github.com/orgs/json-schema-org/projects/16).
  
  - type: textarea
    id: reason-context
    attributes:
      label: What Docs changes are you proposing?
      description: Why do the Docs need this improvement? What is the motivation for this change? How will this change benefit the community?
      placeholder: "I would like to contribute to JSON Schema Docs 📑 by..."
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/json-schema-org/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
