name: Links (Fail Fast)

on:
  push:
  pull_request:
    paths:
      - 'pages/blog/posts/**/*.md'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true