name: Check Links

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: lycheeverse/lychee-action@v1
      - name: Comment Broken Links
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          path: lychee/out.md