name: Links (Fail Fast)

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.event_path, 'pages/blog/posts/') && endsWith(github.event_path, '.md') }}
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true