name: Production Deployment
on:
    push:
        branches:
            - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        name: Publish to Cloudflare Pages
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                submodules: 'recursive'
                
            - name: Corepack enable
              run: corepack enable
        
            - name: Get yarn cache directory path
              id: yarn-cache-dir-path
              run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
            
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'yarn'
        
            - name: Install dependencies
              run: yarn install --immutable

            - name: Build Site
              run: yarn run build
              env:
                NEXT_PUBLIC_ALGOLIA_APP_ID: ${{ secrets.NEXT_PUBLIC_ALGOLIA_APP_ID }}
                NEXT_PUBLIC_ALGOLIA_API_KEY: ${{ secrets.NEXT_PUBLIC_ALGOLIA_API_KEY }}

            - name: Deploy to Cloudflare Pages
              uses: AdrianGonz97/refined-cf-pages-action@v1
              with:
                  apiToken: ${{ secrets.CF_API_TOKEN }}
                  accountId: ${{ secrets.CF_ACCOUNT_ID }}
                  githubToken: ${{ secrets.GITHUB_TOKEN }}
                  projectName: ${{ vars.CF_PROJECT_NAME }}
                  directory: out
                  deploymentName: Production