name: Request Review from Team

on:
  pull_request:
    types: [opened]

jobs:
  assign_team:
    runs-on: ubuntu-latest
    steps:    
    - name: Install dependencies
      run: npm install @octokit/core@5.1.0
        
    - name: Assign Team
      uses: actions/github-script@v7
      env:
        AUTH_TOKEN : ${{ secrets.AUTH_TOKEN }}
        PULL_REQUEST_NUMBER: ${{ github.event.pull_request.number }}
        REPO_NAME: ${{ github.event.repository.name }}
        ORG_NAME: ${{ github.event.repository.owner.login }}
      with:
        script: |
          const Octokit = require('@octokit/core').Octokit;
          const octokit = new Octokit({
            request: { fetch: fetch,},
            auth: process.env.AUTH_TOKEN,
          })
          
          await octokit.request('POST /repos/{orgs}/{repo}/pulls/{pull_number}/requested_reviewers', {
            orgs: process.env.ORG_NAME,
            repo: process.env.REPO_NAME,
            pull_number: process.env.PULL_REQUEST_NUMBER,
            team_reviewers: [
              'web-team'
            ],
            headers: {
              'X-GitHub-Api-Version': '2022-11-28'
            }
          })
